### ISSUE TITLE
Report 中获取不到Author 

### ISSUE THREAD

**Issue by vera3224** [NetEase/arrow#8]
<img src="https://cloud.githubusercontent.com/assets/11629849/25163166/dc23809a-24fa-11e7-80e7-beafdd01c0b7.png" width="50%" height="50%">
我的eclipse设置：Java-Code Style-Code Templates-Type中添加了如下comment，但是报告中并没有获取到

```
/**
* ${tags}
* @author ${user}
* ${date}
* @description
*/
```
请问在eclipse／intellij 中需要做什么修改才能获取到author？

**Comment by kevinkong** [comment]
不需要什么特殊配置，有这个标签应该就可以获取到的，没获取到不知道是不是配置上问题，没有使用最新的改写的监听器么，这部分代码在PowerEmailableReporter.java中的getAuthors方法，可以看看

**Comment by vera3224** [comment]
用的是最新的，我再看下
谢谢回答

**Comment by vera3224** [comment]
找到问题了，ConfigReader中，CONFIGFILE的路径写错了。
Closing as done.
